In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr3=np.arange(10)

In [6]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr2.shape

(2, 3)

In [9]:
arr4=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr4.shape 
arr4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [10]:
arr4.shape

(2, 2, 2)

In [11]:
arr4.size

8

In [13]:
arr5=np.array([1.12,2.34])
arr5.itemsize

8

In [12]:
arr4.itemsize

8

In [14]:
arr4.dtype()

TypeError: 'numpy.dtypes.Int64DType' object is not callable

In [15]:
arr4.dtype

dtype('int64')

In [17]:
arr4.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [18]:
arr5=np.arange(24).reshape(6,4)

In [19]:
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
arr5[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [24]:
for i in arr5:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [ ]:
#arr1-arr2 matlab each element - each element aur * matlab scalar multiplicn


In [25]:
arr1-arr2

ValueError: operands could not be broadcast together with shapes (5,) (2,3) 

In [26]:
arr2>3

array([[False, False, False],
       [ True,  True,  True]])

In [31]:
arr6=np.arange(6).reshape(2,3)
arr7=np.arange(6,12).reshape(3,2)
print(arr6,arr7,arr6.dot(arr7),end='')

[[0 1 2]
 [3 4 5]] [[ 6  7]
 [ 8  9]
 [10 11]] [[ 28  31]
 [100 112]]

##### 

In [33]:
arr5.sum(axis=0)

array([60, 66, 72, 78])

In [34]:
arr5.sum(axis=1)

array([ 6, 22, 38, 54, 70, 86])

In [35]:
np.sin(arr5)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 ]])

In [ ]:
#median aur sin wagera np. form me aur sum max min as given above and exp is e^

In [37]:
for i in np.nditer(arr5):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [38]:
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
arr5.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [40]:
arr4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [41]:
arr4.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
np.hstack((arr4,arr5))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)

In [48]:
arr11=np.arange(9).reshape(3,3)

In [49]:
arr12=np.arange(9,18).reshape(3,3)

In [50]:
np.hstack((arr11,arr12))

array([[ 0,  1,  2,  9, 10, 11],
       [ 3,  4,  5, 12, 13, 14],
       [ 6,  7,  8, 15, 16, 17]])

In [ ]:
#reshape me jo last no hai jaise upar wale cases me last wala 3 agar same hai toh addn possible

In [51]:
#some more cases
a13=np.arange(1).reshape(1,1)
a14=np.arange(20).reshape(4,5)
print(a13)
print(a14)

[[0]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [52]:
a13+a14

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])